export const mockTickets = [
  {
    id: '1234',
    number: 1234,
    title: 'Login page returns 500 error after latest deployment',
    status: 'IN_PROGRESS' as const,
    priority: 'CRITICAL' as const,
    assignee: { name: 'Sarah Chen', avatar: null },
    team: 'Engineering',
    createdAt: '2026-03-18T10:30:00Z',
    updatedAt: '2026-03-20T08:15:00Z',
    category: 'Bug',
    channel: 'Email',
  },
  {
    id: '1233',
    number: 1233,
    title: 'Customer unable to reset password via email link',
    status: 'OPEN' as const,
    priority: 'HIGH' as const,
    assignee: { name: 'James Wilson', avatar: null },
    team: 'Support',
    createdAt: '2026-03-18T09:00:00Z',
    updatedAt: '2026-03-18T14:20:00Z',
    category: 'Bug',
    channel: 'Chat',
  },
  {
    id: '1232',
    number: 1232,
    title: 'Payment gateway timeout on checkout',
    status: 'WAITING' as const,
    priority: 'HIGH' as const,
    assignee: { name: 'Maria Rodriguez', avatar: null },
    team: 'Engineering',
    createdAt: '2026-03-17T16:45:00Z',
    updatedAt: '2026-03-19T11:30:00Z',
    category: 'Incident',
    channel: 'API',
  },
  {
    id: '1231',
    number: 1231,
    title: 'Dashboard charts not loading for enterprise accounts',
    status: 'IN_PROGRESS' as const,
    priority: 'MEDIUM' as const,
    assignee: { name: 'David Kim', avatar: null },
    team: 'Engineering',
    createdAt: '2026-03-17T14:00:00Z',
    updatedAt: '2026-03-20T07:45:00Z',
    category: 'Bug',
    channel: 'Email',
  },
  {
    id: '1230',
    number: 1230,
    title: 'Add CSV export feature to reports page',
    status: 'OPEN' as const,
    priority: 'MEDIUM' as const,
    assignee: { name: 'Emma Johnson', avatar: null },
    team: 'Product',
    createdAt: '2026-03-16T11:20:00Z',
    updatedAt: '2026-03-16T11:20:00Z',
    category: 'Feature Request',
    channel: 'Chat',
  },
  {
    id: '1229',
    number: 1229,
    title: 'Notification emails not sent after ticket resolution',
    status: 'RESOLVED' as const,
    priority: 'MEDIUM' as const,
    assignee: { name: 'Tom Parker', avatar: null },
    team: 'Support',
    createdAt: '2026-03-15T09:30:00Z',
    updatedAt: '2026-03-17T16:00:00Z',
    category: 'Bug',
    channel: 'Email',
  },
  {
    id: '1228',
    number: 1228,
    title: 'Mobile app crashes on iOS 18 when uploading attachments',
    status: 'OPEN' as const,
    priority: 'HIGH' as const,
    assignee: { name: 'Lisa Chang', avatar: null },
    team: 'Mobile',
    createdAt: '2026-03-14T15:00:00Z',
    updatedAt: '2026-03-15T10:30:00Z',
    category: 'Bug',
    channel: 'Phone',
  },
  {
    id: '1227',
    number: 1227,
    title: 'Slow performance on ticket list page with 1000+ records',
    status: 'IN_PROGRESS' as const,
    priority: 'LOW' as const,
    assignee: { name: 'Alex Thompson', avatar: null },
    team: 'Engineering',
    createdAt: '2026-03-13T08:00:00Z',
    updatedAt: '2026-03-18T13:45:00Z',
    category: 'Performance',
    channel: 'API',
  },
  {
    id: '1226',
    number: 1226,
    title: 'Add dark mode support to customer portal',
    status: 'CLOSED' as const,
    priority: 'LOW' as const,
    assignee: { name: 'Priya Patel', avatar: null },
    team: 'Design',
    createdAt: '2026-03-10T14:30:00Z',
    updatedAt: '2026-03-19T17:00:00Z',
    category: 'Feature Request',
    channel: 'Chat',
  },
  {
    id: '1225',
    number: 1225,
    title: 'Two-factor authentication not working for SAML users',
    status: 'RESOLVED' as const,
    priority: 'CRITICAL' as const,
    assignee: { name: 'Carlos Mendez', avatar: null },
    team: 'Security',
    createdAt: '2026-03-09T10:00:00Z',
    updatedAt: '2026-03-12T15:20:00Z',
    category: 'Security',
    channel: 'Email',
  },
];

export const mockTasks = [
  {
    id: 't1',
    title: 'Investigate 500 error root cause in auth service',
    status: 'IN_PROGRESS' as const,
    priority: 'CRITICAL' as const,
    assignee: { name: 'Sarah Chen', avatar: null },
    ticketId: '1234',
    ticketNumber: 1234,
    dueDate: '2026-03-21',
    createdAt: '2026-03-18T10:35:00Z',
    estimatedHours: 4,
  },
  {
    id: 't2',
    title: 'Write unit tests for payment gateway integration',
    status: 'TODO' as const,
    priority: 'HIGH' as const,
    assignee: { name: 'David Kim', avatar: null },
    ticketId: '1232',
    ticketNumber: 1232,
    dueDate: '2026-03-22',
    createdAt: '2026-03-17T16:50:00Z',
    estimatedHours: 6,
  },
  {
    id: 't3',
    title: 'Deploy hotfix to production environment',
    status: 'DONE' as const,
    priority: 'CRITICAL' as const,
    assignee: { name: 'James Wilson', avatar: null },
    ticketId: '1234',
    ticketNumber: 1234,
    dueDate: '2026-03-19',
    createdAt: '2026-03-18T11:00:00Z',
    estimatedHours: 2,
  },
  {
    id: 't4',
    title: 'Update API documentation for v2 endpoints',
    status: 'IN_REVIEW' as const,
    priority: 'MEDIUM' as const,
    assignee: { name: 'Emma Johnson', avatar: null },
    ticketId: null,
    ticketNumber: null,
    dueDate: '2026-03-25',
    createdAt: '2026-03-15T09:00:00Z',
    estimatedHours: 8,
  },
  {
    id: 't5',
    title: 'Performance audit for ticket list component',
    status: 'TODO' as const,
    priority: 'MEDIUM' as const,
    assignee: { name: 'Alex Thompson', avatar: null },
    ticketId: '1227',
    ticketNumber: 1227,
    dueDate: '2026-03-24',
    createdAt: '2026-03-13T08:05:00Z',
    estimatedHours: 5,
  },
  {
    id: 't6',
    title: 'Set up monitoring alerts for auth service',
    status: 'TODO' as const,
    priority: 'HIGH' as const,
    assignee: { name: 'Carlos Mendez', avatar: null },
    ticketId: null,
    ticketNumber: null,
    dueDate: '2026-03-23',
    createdAt: '2026-03-20T08:00:00Z',
    estimatedHours: 3,
  },
  {
    id: 't7',
    title: 'Create onboarding guide for new agents',
    status: 'IN_PROGRESS' as const,
    priority: 'LOW' as const,
    assignee: { name: 'Priya Patel', avatar: null },
    ticketId: null,
    ticketNumber: null,
    dueDate: '2026-03-28',
    createdAt: '2026-03-12T14:00:00Z',
    estimatedHours: 10,
  },
  {
    id: 't8',
    title: 'Review and merge PR for CSV export feature',
    status: 'IN_REVIEW' as const,
    priority: 'MEDIUM' as const,
    assignee: { name: 'Tom Parker', avatar: null },
    ticketId: '1230',
    ticketNumber: 1230,
    dueDate: '2026-03-22',
    createdAt: '2026-03-18T15:00:00Z',
    estimatedHours: 2,
  },
];

export const mockActivityFeed = [
  {
    id: 'a1',
    user: 'Sarah Chen',
    action: 'assigned ticket',
    target: '#1234',
    detail: 'to herself',
    time: '2 hours ago',
  },
  {
    id: 'a2',
    user: 'James Wilson',
    action: 'resolved ticket',
    target: '#1229',
    detail: 'Notification emails issue',
    time: '4 hours ago',
  },
  {
    id: 'a3',
    user: 'Maria Rodriguez',
    action: 'added comment to',
    target: '#1232',
    detail: 'Payment gateway timeout',
    time: '5 hours ago',
  },
  {
    id: 'a4',
    user: 'System',
    action: 'SLA breach detected for',
    target: '#1233',
    detail: 'Customer password reset',
    time: '6 hours ago',
  },
  {
    id: 'a5',
    user: 'David Kim',
    action: 'created task for',
    target: '#1231',
    detail: 'Dashboard performance issue',
    time: '8 hours ago',
  },
];

export const mockWorkflows = [
  {
    id: 'w1',
    name: 'Bug Fix Process',
    description:
      'Standard process for triaging and resolving software bugs from report to closure',
    stepCount: 6,
    activeInstances: 8,
    status: 'active' as const,
    updatedAt: '2026-03-15',
    category: 'Engineering',
  },
  {
    id: 'w2',
    name: 'Customer Onboarding',
    description:
      'Guides new customers through account setup, training, and first-use milestones',
    stepCount: 8,
    activeInstances: 3,
    status: 'active' as const,
    updatedAt: '2026-03-10',
    category: 'Customer Success',
  },
  {
    id: 'w3',
    name: 'Change Request',
    description:
      'Formal process for evaluating, approving, and implementing system changes',
    stepCount: 5,
    activeInstances: 2,
    status: 'active' as const,
    updatedAt: '2026-02-28',
    category: 'Operations',
  },
  {
    id: 'w4',
    name: 'Escalation Protocol',
    description:
      'Automated escalation path for critical issues requiring management intervention',
    stepCount: 4,
    activeInstances: 0,
    status: 'inactive' as const,
    updatedAt: '2026-02-10',
    category: 'Support',
  },
];

export const mockKBArticles = [
  {
    id: 'kb1',
    title: 'How to reset your password',
    excerpt:
      'Step-by-step guide for resetting your account password via email or SMS verification',
    author: 'Support Team',
    date: '2026-03-01',
    views: 1243,
    category: 'How-To',
  },
  {
    id: 'kb2',
    title: 'Troubleshooting login issues',
    excerpt:
      'Common causes for login failures and how to resolve them including 2FA issues',
    author: 'Sarah Chen',
    date: '2026-02-20',
    views: 892,
    category: 'Troubleshooting',
  },
  {
    id: 'kb3',
    title: 'Understanding SLA policies',
    excerpt:
      'Learn how SLA response and resolution times are calculated and what happens on breach',
    author: 'Operations Team',
    date: '2026-02-15',
    views: 456,
    category: 'Policies',
  },
  {
    id: 'kb4',
    title: 'Getting started with workflows',
    excerpt:
      'Introduction to creating and managing automation workflows for ticket processing',
    author: 'Product Team',
    date: '2026-02-10',
    views: 678,
    category: 'How-To',
  },
  {
    id: 'kb5',
    title: 'API integration guide',
    excerpt:
      'Complete reference for integrating third-party systems with the TaskFlow API',
    author: 'Engineering Team',
    date: '2026-01-25',
    views: 334,
    category: 'General',
  },
];

export const mockTeams = [
  {
    id: 'team1',
    name: 'Engineering',
    lead: 'Sarah Chen',
    memberCount: 8,
    members: ['SC', 'DK', 'AT', 'JW', 'CM', 'LF', 'BM', 'RK'],
    description: 'Handles technical bugs, performance issues, and feature development',
  },
  {
    id: 'team2',
    name: 'Customer Support',
    lead: 'James Wilson',
    memberCount: 5,
    members: ['JW', 'MR', 'TP', 'EJ', 'PP'],
    description: 'Front-line support for customer inquiries and issue resolution',
  },
];

export const mockSLAPolicies = [
  {
    id: 'sla1',
    name: 'Critical Priority',
    responseTime: '1 hour',
    resolutionTime: '4 hours',
    conditions: 'Priority = Critical',
    active: true,
  },
  {
    id: 'sla2',
    name: 'Standard',
    responseTime: '4 hours',
    resolutionTime: '24 hours',
    conditions: 'Priority = High or Medium',
    active: true,
  },
  {
    id: 'sla3',
    name: 'Low Priority',
    responseTime: '24 hours',
    resolutionTime: '72 hours',
    conditions: 'Priority = Low',
    active: false,
  },
];

export const mockAutomationRules = [
  {
    id: 'auto1',
    name: 'Critical Escalation',
    nlRule:
      'When a Critical ticket is open for more than 1 hour, escalate to the team manager and send an email notification',
    trigger: 'Time-based',
    active: true,
    lastRun: '2026-03-20T08:00:00Z',
  },
  {
    id: 'auto2',
    name: 'Auto-Assign by Category',
    nlRule:
      'When a new Bug ticket is created, automatically assign it to the Engineering team and set priority based on description',
    trigger: 'Ticket Created',
    active: true,
    lastRun: '2026-03-20T09:45:00Z',
  },
  {
    id: 'auto3',
    name: 'Resolve Stale Tickets',
    nlRule:
      'When a ticket has been in Waiting status for more than 7 days with no customer response, mark it as Resolved and send a closure notification',
    trigger: 'Time-based',
    active: false,
    lastRun: '2026-03-13T00:00:00Z',
  },
];

export const mockUsers = [
  {
    id: 'u1',
    name: 'Sarah Chen',
    email: 'sarah.chen@taskflow.io',
    role: 'MANAGER',
    team: 'Engineering',
    active: true,
    joinedAt: '2024-01-15',
  },
  {
    id: 'u2',
    name: 'James Wilson',
    email: 'james.wilson@taskflow.io',
    role: 'MANAGER',
    team: 'Customer Support',
    active: true,
    joinedAt: '2024-02-01',
  },
  {
    id: 'u3',
    name: 'Maria Rodriguez',
    email: 'maria.r@taskflow.io',
    role: 'AGENT',
    team: 'Engineering',
    active: true,
    joinedAt: '2024-03-10',
  },
  {
    id: 'u4',
    name: 'David Kim',
    email: 'david.kim@taskflow.io',
    role: 'AGENT',
    team: 'Engineering',
    active: true,
    joinedAt: '2024-04-05',
  },
  {
    id: 'u5',
    name: 'Emma Johnson',
    email: 'emma.j@taskflow.io',
    role: 'AGENT',
    team: 'Customer Support',
    active: false,
    joinedAt: '2024-05-20',
  },
];
